# Generated by Django 3.2 on 2021-04-15 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=250, verbose_name='Слаг')),
                ('url', models.URLField(verbose_name='Ссылка на оригинальную картинку')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Создана')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создана')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_created', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('users_like', models.ManyToManyField(related_name='images_liked', to=settings.AUTH_USER_MODEL, verbose_name='Юзеры поставили лайк')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
                'ordering': ('created',),
            },
        ),
    ]
