# Generated by Django 3.2 on 2021-04-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_total_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
